### ISSUE TITLE
Installation fixes

### ISSUE THREAD

**Issue by BradleyKirton** [JannieI/canvas#3]
From a fresh clone I needed to do the following to get the application up and running.

- npm uninstall angular-cli --save-dev
    - The angular-cli is deprecated and replaced with @angular/cli
- npm install @angular/cli --save-dev
- npm install vega --save

Next up I had to make a change to the angular-cli.json file. See before and after below.

Before:
```json
      "environments": {
       "source": "environments/environment.ts",
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
```

After:
```json
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
```

Can you please try apply these changes and push again? I will then continue the mountain climb :mount_fuji:

**Comment by JannieI** [comment]
I can, but will I install ng4 or ng2 ?   I think the npm install will get
the latest version - or will it use some packages.json?   I would prefer to
stay on 2 until Canvas is good, then migrate.

**Comment by BradleyKirton** [comment]
To run with the local ng use the following:

```bash
./node_modules/@angular/cli/bin/ng serve
```

**Comment by JannieI** [comment]
Installed @CLI with Bradley
