### ISSUE TITLE
Root component

### ISSUE THREAD

**Issue by BradleyKirton** [JannieI/canvas#5]
Just making some changes in a branch and noticed the following:

The loadMenu function returns MenuItems[] which we assign to this.menuItems. However in the function we assign the items to this.menuItems. Therefore we are actually running the following when calling loadMenu.

```typescript
this.menuItems = this.menuItems;
```

I have made a change in the branch I am working on but I am not sure if we will even merge these for now.

Given this, I can make another branch and apply the change and then we can learn how merge works too :p Or if you like you can fix. 

What do you think?

**Comment by JannieI** [comment]
Hi Bradley,
i am happy to make the change for now.  I suggest you use your branch to
play and get all working (given that it may change a few times).  Once
done, we sit together, apply the changes once to master, make a branch each
(one for serias dev and maybe one for play-play) and figure out merging.

Hope that works for you.

Kind regards,
Jannie

**Comment by BradleyKirton** [comment]
Good stuff :+1:
